config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                    Controller#Action
#          root GET    /                              home#index
#     companies GET    /companies(.:format)           companies#index
#               POST   /companies(.:format)           companies#create
#   new_company GET    /companies/new(.:format)       companies#new
#  edit_company GET    /companies/:id/edit(.:format)  companies#edit
#       company GET    /companies/:id(.:format)       companies#show
#               PATCH  /companies/:id(.:format)       companies#update
#               PUT    /companies/:id(.:format)       companies#update
#               DELETE /companies/:id(.:format)       companies#destroy
#    categories GET    /categories(.:format)          categories#index
#               POST   /categories(.:format)          categories#create
#  new_category GET    /categories/new(.:format)      categories#new
# edit_category GET    /categories/:id/edit(.:format) categories#edit
#      category GET    /categories/:id(.:format)      categories#show
#               PATCH  /categories/:id(.:format)      categories#update
#               PUT    /categories/:id(.:format)      categories#update
#               DELETE /categories/:id(.:format)      categories#destroy
#      products GET    /products(.:format)            products#index
#               POST   /products(.:format)            products#create
#   new_product GET    /products/new(.:format)        products#new
#  edit_product GET    /products/:id/edit(.:format)   products#edit
#       product GET    /products/:id(.:format)        products#show
#               PATCH  /products/:id(.:format)        products#update
#               PUT    /products/:id(.:format)        products#update
#               DELETE /products/:id(.:format)        products#destroy
#

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get '/gemfile', to: 'home#gemfile', as: 'gemfile'

  resources :companies
  resources :categories
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                :integer          not null, primary key
#  name              :string
#  slogan            :string
#  mission_statement :string
#  street            :string
#  zip_code          :string
#  city              :string
#  country           :string
#  revenue           :decimal(, )
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Company < ApplicationRecord
  validates :name, presence: true
  validates :revenue, numericality: true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :price, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.order('LOWER(name)')
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.order('LOWER(name)')
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: "#{@company.name} was successfully created."
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: "#{@company.name} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: "#{@company.name} was successfully destroyed."
  end

  private

  def set_company
    @company = Company.find(params[:id])
  rescue
    redirect_to root_url
  end

  def company_params
    params.require(:company).permit(
      :name,
      :slogan,
      :mission_statement,
      :street,
      :zip_code,
      :city,
      :country,
      :revenue
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @companies_count = Company.count
    @categories_count = Category.count
    @products_count = Product.count
  end

  def gemfile
    @gemfile = ""
    File.open("#{Rails.root}/Gemfile.lock", 'r') do |f|
      f.each_line do |line|
        @gemfile << line
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.order('LOWER(name)')
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories <small>(<%= @categories.count %>)</small></h1>

<%= link_to 'New Category', new_category_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th># of Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.products.count %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Products in this category:</strong>
  <%= @category.products.count %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slogan %><br>
    <%= f.text_field :slogan %>
  </div>

  <div class="field">
    <%= f.label :mission_statement %><br>
    <%= f.text_field :mission_statement %>
  </div>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :revenue %><br>
    <%= f.number_field :revenue, step: :any %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies <small>(<%= @companies.count %>)</small></h1>

<%= link_to 'New Company', new_company_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Slogan</strong>
  <%= @company.slogan %>
</p>

<p>
  <strong>Mission Statement</strong>
  <%= @company.mission_statement %>
</p>

<p>
  <strong>Street</strong>
  <%= @company.street %>
</p>

<p>
  <strong>Zip Code</strong>
  <%= @company.zip_code %>
</p>

<p>
  <strong>City</strong>
  <%= @company.city %>
</p>

<p>
  <strong>Country</strong>
  <%= @company.country %>
</p>

<p>
  <strong>Revenue</strong>
  <%= @company.revenue %>
</p>



<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/home/gemfile.html.erb
<pre><code><%= @gemfile %></code></pre>

app/views/home/index.html.erb
<h1>RailsPlay</h1>
<p>
  <em>RailsPlay</em> is a basic <%= link_to "Ruby on Rails", "http://rubyonrails.org" %> playground. For more info, visit <%= link_to "RailsPlay on Github", "https://github.com/nicoschuele/railsplay" %>.
</p>

<hr/>

<h2>Models</h2>

<h3>&gt; Single model</h3>

<h4>Company</h4>
<p>
  <small>
    Currently <%= pluralize(@companies_count, 'record') %> in the database.
  </small>
</p>
<ul>
  <li>name: <em>string</em></li>
  <li>slogan: <em>string</em></li>
  <li>mission_statement: <em>string</em></li>
  <li>street: <em>string</em></li>
  <li>zip_code: <em>string</em></li>
  <li>city: <em>string</em></li>
  <li>country: <em>string</em></li>
  <li>revenue: <em>decimal</em></li>
  <li>created_at: <em>datetime</em></li>
  <li>updated_at: <em>datetime</em></li>
</ul>

<h3>&gt; Two models with a one-to-many relationship</h3>
<h4>Category</h4>
<p>
  <small>
    Currently <%= pluralize(@categories_count, 'record') %> in the database.
  </small>
</p>
<ul>
  <li>name: <em>string</em></li>
  <li>description: <em>text</em></li>
  <li>created_at: <em>datetime</em></li>
  <li>updated_at: <em>datetime</em></li>
</ul>

<h4>Product</h4>
<p>
  <small>
    Currently <%= pluralize(@products_count, 'record') %> in the database.
  </small>
</p>
<ul>
  <li>name: <em>string</em></li>
  <li>description: <em>text</em></li>
  <li>price: <em>decimal</em></li>
  <li>category_id: <em>integer</em></li>
  <li>created_at: <em>datetime</em></li>
  <li>updated_at: <em>datetime</em></li>
</ul>

<hr/>

<h2>Versions &amp; Environment</h2>
<%= render 'layouts/version' %>

<hr/>

<h2>Local info</h2>
<%= render 'layouts/info' %>

app/views/layouts/_info.html.erb
<ul>
  <li>User Agent: <%= request.env['HTTP_USER_AGENT'] %></li>
  <li>Local Date &amp; Time: <%= Time.now %></li>
  <li>Browser language: <%= request.env['HTTP_ACCEPT_LANGUAGE'] %></li>
  <li>Client IP: <%= request.remote_ip %></li>
</ul>

app/views/layouts/_navigation.html.erb
<p>
  <%= link_to "Home", root_url %> |
  <%= link_to "Companies", companies_path %> |
  <%= link_to "Categories", categories_path %> |
  <%= link_to "Product", products_path %>
</p>
<hr/>

app/views/layouts/_version.html.erb
<ul>
  <li><strong>Ruby:</strong> <%= "#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL}" %></li>
  <li><strong>Rails:</strong> <%= Rails.version %></li>
  <li><strong>Rails environment:</strong> <%= Rails.env %></li>
  <li><%= link_to "View Gemfile.lock", gemfile_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsplay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, step: :any %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products <small>(<%= @products.count %>)</small></h1>

<%= link_to 'New Product', new_product_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to product.category.name, product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to "#{@product.category.name}", @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>